### ISSUE TITLE
how can I build rtack on 64 bit machine?

### ISSUE THREAD

**Issue by lkx007** [JefGrailet/rtrack#1]
when I execute make in rtrack/v1/Code/Release
the following error orrurs.

/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/32/libgcc_s.so when searching
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.2/libgcc_s.so when searching fo
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.2/32/libgcc_s.so when searching
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/libgcc_s.so when searching fo
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
make: *** [rtrack] Error 1
[root@localhost Release]# 

my machine is cento7 as follows.
[root@localhost Release]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[root@localhost Release]# uname -a
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost Release]# 
can anyone help me , thanks a lot.

**Comment by JefGrailet** [comment]
Hi lkx007,

By the looks of it (I don't see the full error messages), you are missing 32-bit equivalent of the default libraries. Indeed, RTrack, like TreeNET is designed to be a 32-bit application because it's supposed to run on PlanetLab machines, which have 32-bit environment most of the time. After a quick search, you should be able to install them on your OS with some additional command lines. Maybe this command could be a start:

yum install libstdc++.i686

Alternatively, if you want to run RTrack from PlanetLab, consider compiling it in a (32-bit) virtual machine and directly upload the executable on the PlanetLab nodes of your choice. I hope this helps.

Best regards,

Jean-François

**Comment by lkx007** [comment]
@JefGrailet  Thanks a lot for your appreciate reply.
I hava install libstdc++.i686 and the same problem occurs.
but after I create the folloing link , I can make successfully.

ln -s /lib/libgcc_s.so.1 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/32/libgcc_s.so 
ln -s /lib/libstdc++.so.6.0.19 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/32/libstdc++.so

Thank you very much.
